POST http://localhost:8080/photoviewer/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

PUT http://localhost:8080/photoviewer/api/photo/Joergensen_0001_TN.jpg
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2MzcyNDc1NjMsImlhdCI6MTYzNzI0NTc2MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.ax8nRCp1Y7JfoIfpnHoVcZKcbPd9OCnHxvc_BIm3Lf8

{
  "location": "https://h-mogensen.dk/Joergensen/",
  "name": "AAAAAA",
  "viewNo": 2,
  "description": "DETTE EER EN TEST",
  "tags": [{"name":"mors"},{"name":"thOrkild22"}, {"name":"hello"}]
}

###
POST http://localhost:8080/photoviewer/api/photo/
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2MzcyNDc1NjMsImlhdCI6MTYzNzI0NTc2MywiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.ax8nRCp1Y7JfoIfpnHoVcZKcbPd9OCnHxvc_BIm3Lf8

{
  "location": "https://h-mogensen.dk/Joergensen/",
  "name": "AAAAAA",
  "description": "Købmandsgården i Sønder Dråby, Mors. Maleri",
  "tags": [{"name":"mors"},{"name":"thOrkild22"}, {"name":"hello"}]
}

###
GET http://localhost:8080/photoviewer/api/photo/property/location/all
###

GET http://localhost:8080/photoviewer/api/photo
###
